# Generated by Django 5.2.4 on 2025-07-23 22:27

import django.db.models.deletion
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место для выполнения привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите время когда выполнять привычку", verbose_name="Время для выполнения"
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        help_text="Опишите действие, представляющее привычку", verbose_name="Описание действия"
                    ),
                ),
                ("is_pleasant_habit", models.BooleanField(default=False, verbose_name="Приятная привычка?")),
                (
                    "periodicity_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Добавьте приятную привычку к полезной",
                        validators=[habits.validators.validate_periodicity_days],
                        verbose_name="Периодичность (дней)",
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение")),
                (
                    "execution_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Укажите время на выполнение привычки (в секундах, для полезной - не более 120 сек)",
                        null=True,
                        validators=[habits.validators.validate_execution_time],
                        verbose_name="Время на выполнение (в секундах)",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False, help_text="Опубликуйте привычку", verbose_name="Публикация привычки"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший привычку",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Добавьте связанную приятную привычку",
                        limit_choices_to={"is_pleasant_habit": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pleasurable_habits",
                        to="habits.habit",
                        verbose_name="Связанная c полезной приятная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
